name: 'Publish'
description: 'Publish a WeChat miniprogram'
inputs:
  project-path:
    description: The root directory of WeChat miniprogram.
  version:
    description: >
      Release version.
      If it is empty and package.json exists, the version in package.json will be used.
runs:
  using: 'composite'
  steps:
    - run: npm i
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: npm run build
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: node ${{ github.action_path }}/dist
      shell: bash
