name: 'Publish'
description: 'Publish a WeChat miniprogram'
inputs:
  project-path:
    description: The root directory of WeChat miniprogram.
  ssh-key:
    description: >
      SSH key used to upload the miniprogram.
      Please download it from WeChat Public Platform (https://mp.weixin.qq.com) and configure it as a secret.
    required: true
  version:
    description: >
      Release version.
      If it is empty and package.json exists, the version in package.json will be used.
runs:
  using: 'composite'
  steps:
    - run: npm i --production
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: node dist
      shell: bash
      working-directory: ${{ github.action_path }}
