name: Publish WeChat Miniprogram
description: Publish your WeChat miniprogram to Wechat Platform
inputs:
  upload-key:
    description: A private key used to authenticate and upload your miniprogram project.
  project-path:
    description: >
      The root directory of WeChat miniprogram.
      Default: '.'
  version:
    description: >
      Release version.
      If it is empty and package.json exists, the version in package.json will be used.
runs:
  using: composite
  steps:
    - run: npm i
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: npm run build
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: node ${{ github.action_path }}/dist
      shell: bash
