name: 'Publish'
description: 'Publish a WeChat miniprogram'
inputs:
  ssh-key:
    description: >
      SSH key used to upload the miniprogram.
      Please download it from WeChat Public Platform (https://mp.weixin.qq.com) and configure it as a secret.
    required: true
  version:
    description: >
      Release version.
      If it is empty and package.json exists, the version in package.json will be used.
runs:
  using: node12
  main: dist/index.js
